name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.ACCESS }}
      - name: Install npm packages
        run: npm install
      - name: "Build containers"
        run: npm run build
      - name: "Run the tests"
        run: npm test
